name: social
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0-alpha+20250615

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^6.5.0
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter_local_notifications: ^19.2.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.0
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  provider: ^6.1.5
  record: ^6.0.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shorebird_code_push: ^2.0.4

  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
