name: social
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0-alpha+110

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^6.5.0
  app_settings: ^6.1.1
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.0
  camera: ^0.11.0+2
  chewie: ^1.11.3
  cloud_firestore: ^5.6.7
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: 5b2c7ae
  file_picker: ^10.1.2
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^19.1.0
  flutter_email_sender: ^7.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  provider: ^6.1.5
  record: ^6.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  video_player: ^2.9.5
  video_thumbnail:
      git:
        url: https://github.com/adrianHerreraa/video_thumbnail.git
        ref: 368a6b3

  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
