name: social
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.43-alpha+63

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^6.3.2
  app_settings: ^5.1.1
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.0
  camera: ^0.11.0+2
  chewie: ^1.8.5
  cloud_firestore: ^5.4.4
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master
  file_picker: ^8.1.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.4
  flutter_email_sender: ^6.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  record: ^5.2.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3

  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
