name: social
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.14-alpha+14

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^6.3.2
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.0
  camera: ^0.11.0+2
  chewie: ^1.8.5
  contacts_service: ^0.6.3
  cloud_firestore: ^5.4.0
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master
  file_picker: ^8.1.2      
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  ffmpeg_kit_flutter: ^6.0.3
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.2
  flutter_email_sender: ^6.0.3
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  record: ^5.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3

  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
